{
  "headers": {
    "requester_id": "11",
    "authorization": "Basic bWQ6bTE0",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.25.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "5ffc678a-1bbc-4f97-a82f-4711fb0294aa",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "179"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/revise",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/revise",
  "relativePath": "/revise",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/revise",
  "rawRequestPath": "/revise",
  "remoteAddress": "/127.0.0.1:62619",
  "requestPath": "/revise"
}